version: '3'
services:
  s3-backup:
    image: ghcr.io/tacten/s3-backup:postgresql 
    volumes:
      - backups:/s3
      - uploads:/uploads
    env_file:
      - .env

volumes:
  backups:
  uploads:

networks:
  default:
    name: erpnext-common-infra
    external: true
