name: Build latest images

on:
  push:
    paths-ignore:
    - '*docker-compose*'
    - 'README.md'
    - '.gitignore'
    tags:
    - "v*"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, erpnext]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/bake-action@v4.0.0
      with:
        push: true
        no-cache: true
        # set: "*.platform=linux/amd64,linux/arm64"
        # set: |
        #   *.tags=${{ steps.meta.outputs.tags }}
        #   *.labels=${{ steps.meta.outputs.labels }}
        #   *.platform=linux/amd64,linux/arm64
      env:
        REGISTRY_NAME: ghcr.io/${{ steps.get-repo.outputs.GITHUB_OWNER }}
        VERSION: ${{  github.ref_name }}